# Generated by Django 5.1 on 2024-08-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_radiation_avg', models.FloatField()),
                ('solar_panel_last', models.FloatField()),
                ('precipitation_sum', models.FloatField()),
                ('battery_last', models.FloatField()),
                ('hc_serial_number_last', models.FloatField()),
                ('hc_air_temperature_avg', models.FloatField()),
                ('hc_air_temperature_max', models.FloatField()),
                ('hc_air_temperature_min', models.FloatField()),
                ('hc_relative_humidity_avg', models.FloatField()),
                ('hc_relative_humidity_max', models.FloatField()),
                ('hc_relative_humidity_min', models.FloatField()),
                ('dew_point_avg', models.FloatField()),
                ('dew_point_min', models.FloatField()),
                ('vpd_avg', models.FloatField()),
                ('vpd_min', models.FloatField()),
                ('delta_t_avg', models.FloatField()),
                ('delta_t_max', models.FloatField()),
                ('delta_t_min', models.FloatField()),
                ('sunshine_duration_time', models.FloatField()),
                ('usonic_wind_speed_avg', models.FloatField()),
                ('usonic_wind_speed_max', models.FloatField()),
                ('usonic_wind_dir_last', models.FloatField()),
                ('wind_gust_max', models.FloatField()),
                ('et0_result', models.FloatField(blank=True, null=True)),
                ('wind_orientation_result', models.FloatField()),
                ('sunrise_result', models.FloatField()),
                ('sunset_result', models.FloatField()),
                ('midnight_result', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensors', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backrafApp.sensordata')),
            ],
        ),
    ]
