from django.db import models

class SensorData(models.Model):
    solar_radiation_avg = models.FloatField(null=True, blank=True)
    solar_panel_last = models.FloatField(null=True, blank=True)
    precipitation_sum = models.FloatField(null=True, blank=True)
    battery_last = models.FloatField(null=True, blank=True)
    hc_serial_number_last = models.FloatField(null=True, blank=True)
    hc_air_temperature_avg = models.FloatField(null=True, blank=True)
    hc_air_temperature_max = models.FloatField(null=True, blank=True)
    hc_air_temperature_min = models.FloatField(null=True, blank=True)
    hc_relative_humidity_avg = models.FloatField(null=True, blank=True)
    hc_relative_humidity_max = models.FloatField(null=True, blank=True)
    hc_relative_humidity_min = models.FloatField(null=True, blank=True)
    dew_point_avg = models.FloatField(null=True, blank=True)
    dew_point_min = models.FloatField(null=True, blank=True)
    vpd_avg = models.FloatField(null=True, blank=True)
    vpd_min = models.FloatField(null=True, blank=True)
    delta_t_avg = models.FloatField(null=True, blank=True)
    delta_t_max = models.FloatField(null=True, blank=True)
    delta_t_min = models.FloatField(null=True, blank=True)
    sunshine_duration_time = models.FloatField(null=True, blank=True)
    usonic_wind_speed_avg = models.FloatField(null=True, blank=True)
    usonic_wind_speed_max = models.FloatField(null=True, blank=True)
    usonic_wind_dir_last = models.FloatField(null=True, blank=True)
    wind_gust_max = models.FloatField(null=True, blank=True)
    et0_result = models.FloatField(null=True, blank=True)
    wind_orientation_result = models.FloatField(null=True, blank=True)
    sunrise_result = models.FloatField(null=True, blank=True)
    sunset_result = models.FloatField(null=True, blank=True)
    midnight_result = models.FloatField(null=True, blank=True)

class StationData(models.Model):
    station_id = models.CharField(max_length=100)
    date = models.DateTimeField()
    sensors = models.OneToOneField(SensorData, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
